project:
  type: book
  output-dir: docs

execute:
  warning: false
  message: false
  error: false

book:
  title: "Reforma fiscală ca alternativă la austeritate"
  subtitle: "Draft la studiul FES cu acelaşi nume"
  author: "Petre Buciu"
  date: "6/07/2023"
  chapters:
    - index.qmd
    - Generalitati.qmd
    - ratele_impozitarii.qmd
    - distributional.qmd
    - Impozit_profit.qmd
    - tipuri_taxe.qmd
    - tranzactii_imobiliare.qmd
    - calcule_finale.qmd


format:
  html:
    theme: cosmo
    cover-image: cover.png
    css: style.css
    code-fold: true
    code-summary: "Arată codul"
    
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
  docx:
    toc: true
    toc-depth: 3
    crossref:
      chapters: true
editor: visual

